services:
  webserver:
    build: .
    container_name: aulasegura-nestjs
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - TZ=Europe/Madrid
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - NODE_ENV=${NODE_ENV}
    ports:
      - ${WEB_SERVER_PORT}:3000
    working_dir: /web
    command: pm2-runtime start pm2.json
    volumes:
      - .:/web
      - ./imageserver/images:/app/images
    networks:
      - aulasegura-network

  database:
    image: yobasystems/alpine-mariadb:11.4.5
    container_name: aulasegura-mariadb
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=Europe/Madrid
    volumes:
    - mariadb_data:/var/lib/mysql
    # - ./db:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:3306"
    networks:
      - aulasegura-network

  phpmyadmin:
    image: phpmyadmin:apache
    container_name: aulasegura-phpmyadmin
    restart: unless-stopped
    depends_on:
      - database
    environment:
      PMA_HOST: ${DB_HOST}                        # nombre del servicio de tu MySQL
      PMA_USER: ${DB_USER}                        # opcional
      PMA_PASSWORD: ${DB_PASSWORD}                # opcional
      UPLOAD_LIMIT: 256M                          # opcional, límite de subida de archivos .sql
      BLOWFISH_SECRET: "quelafuerzateacompañe"    # opcional, clave de cifrado para asegurar las cookies de autenticación
    ports:
      - "8085:80"                             
    networks:
      - aulasegura-network

  imageserver:
    image: nginx:1.29.3-alpine
    container_name: aulasegura-nginx-images
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - ./imageserver/images:/srv/images:ro
      - ./imageserver/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - aulasegura-network

volumes:
  mariadb_data:
    driver: local

networks:
  aulasegura-network:
    driver: bridge
